# Generated by Django 4.2.5 on 2023-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todooapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1212-02-25'),
            preserve_default=False,
        ),
    ]
